### ISSUE TITLE
Create a pre-release

### ISSUE THREAD

**Issue by matentzn** [iovka/shex-java#20]
Hey, I need a simple way to just run shex validation on the command line; I make use of docker pipelines and this mvn package workflow, especially with version numbers involved on the created jar that are not under my control, is a brittle process; furthermore, I can't even build it on my normal developer machine (NoClassDefFound, so I assume its the ancient Java 8 version I am using). Would you mind simply building shex-java and creating a github pre-release? And maybe providing a simple documentation page outlining the parameters that can be used. Thanks.

**Comment by iovka** [comment]
Hi,
I would like to make sure that I understand correctly your problem and the possible solutions. Can we discuss about that in a more interactive way (chat, voice). Please contact me by mail at iovka.boneva@univ-lille.fr

**Comment by iovka** [comment]
It is now possible to construct a jar of shex-java that includes all referenced libraries.
Moreover, the command line tool was a bit improved, it now allows to output a result shape map.

To build the jar and print help information, use the following

```
git clone https://github.com/iovka/shex-java.git
cd shex-java/shex
mvn clean compile assembly:single
cd target 
java -cp shexjava-core-1.3beta.jar fr.inria.lille.shexjava.commandLine.Validate -h
```
