### ISSUE TITLE
update jena version?

### ISSUE THREAD

**Issue by goodb** [iovka/shex-java#6]
I'm trying to integrate shex-java into an existing project and have a conflict.  shex-java is on version 3.0.0 of Jena and my existing project needs the current 3.11.0 .  I can resolve, but perhaps it would be good to update the Jena version in the project pom?

shex-jena seems to be okay running 3.11.0 when I test it.

**Comment by jdusart** [comment]
Yes, there shouldn't be any problem since the only place I am using Jena in the project is in the test.
I will update it in the next release.

**Comment by jdusart** [comment]
I have released version 1.2.3 with jena updated at version 3.11.0.
